(source (official cli))
(config username "Noah Summers")
(config project_name romanum)
(config email ns@rewritable.me)
(config npm_username noahsummers)
(config github_username noahsummers)
(config project_description
 "A library and CLI for the decoding and encoding of Roman numerals")
(config package_manager Opam)
(config ci_cd Github)
(config syntax OCaml)
(config project_snake romanum)
(config project_slug romanum)
(config test_framework Alcotest)
